import re
from typing import Tuple, Optional

# Standard disclaimer text to append to all outbound responses
DISCLAIMER_TEXT = (
    "\n\n---\n"
    "**Disclaimer**: *This analysis is generated by an AI assistant for educational, research, and Kaggle Capstone "
    "demonstration purposes only. It is NOT financial advice, investment advice, or trading recommendations. "
    "Cryptocurrencies are highly speculative and volatile. Do your own research (DYOR) before making investment decisions.*"
)

# Inbound guardrail rules
BANNED_KEYWORDS = [
    r"\bbuy\b",
    r"\bsell\b",
    r"\btrade\b",
    r"\binvest\b",
    r"\bleverage\b",
    r"\bshort\b",
    r"\blong\b",
    r"\bpurchase\b",
    r"\bexecute\b",
    r"\btransaction\b",
    r"\bportfolio management\b",
    r"\btransfer\b",
    r"\bswap\b"
]

class FinancialGuardrails:
    """
    Implements security checks for inputs and outputs of the cryptocurrency analyst agent.
    """
    
    @staticmethod
    def evaluate_input(user_prompt: str) -> Tuple[bool, Optional[str]]:
        """
        Scans incoming prompts for transaction execution or financial advice requests.
        
        Returns:
            (is_allowed, warning_message)
        """
        cleaned_prompt = user_prompt.lower().strip()
        
        # 1. Check for transaction execution or direct trading requests
        for pattern in BANNED_KEYWORDS:
            if re.search(pattern, cleaned_prompt):
                trigger_word = re.findall(pattern, cleaned_prompt)[0]
                warning = (
                    f"Action Blocked: The system detected a transaction/trading keyword ('{trigger_word}'). "
                    "This application operates strictly under read-only mode and cannot execute buy/sell orders, "
                    "manage wallets, or suggest trading actions."
                )
                return False, warning
                
        # 2. Check for requests seeking direct personal asset management
        personal_advising_phrases = [
            "what should i do with my",
            "allocate my portfolio",
            "should i hold",
            "i should hold",
            "should i buy",
            "should i sell",
            "make me money",
            "is it safe to"
        ]
        for phrase in personal_advising_phrases:
            if phrase in cleaned_prompt:
                warning = (
                    "Advice Blocked: The system cannot provide customized personal asset recommendations. "
                    "You may ask for price history, general market trends, or public sentiment statistics."
                )
                return False, warning

        return True, None

    @staticmethod
    def apply_output_guardrails(agent_response: str) -> str:
        """
        Appends mandatory financial disclaimer to all outgoing responses.
        """
        if DISCLAIMER_TEXT not in agent_response:
            return agent_response + DISCLAIMER_TEXT
        return agent_response

    @staticmethod
    def sanitize_symbol(token_query: str) -> str:
        """
        Sanitizes search query input to prevent injection attacks or command escapes.
        """
        # Strip special characters, allow only alpha-numeric and dashes/underscores
        return re.sub(r"[^a-zA-Z0-9\-\_]", "", token_query)
